title: " "
subtitle: " "
author: "Quinton Quagliano, M.S."
# SECTION: PowerPoint opts
format: 
  pptx: 
    reference-doc: ./gv_template.pptx
    slide-level: 2
    toc: true
    toc-depth: 1
    number-sections: true
    keep-md: true
    keep-ipynb: true
# SECTION: Exec opts
execute:
  echo: false
  warning: false
  message: false
  eval: false
  output: false
  cache: false
  freeze: false
# SECTION: Language opts
lang: en-US
fontfamily: "Times New Roman"
# SECTION: Metadata opts
keywords:
  - "placeholder"
description: "placeholder"
subject: "placeholder"
category: "placeholder"
